name: Nocturne
options:
  bundleIdPrefix: com.dcj
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  groupSortPosition: top

targets:
  Nocturne:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: Nocturne
        PRODUCT_BUNDLE_IDENTIFIER: com.dcj.nocturne
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0.1"
        CURRENT_PROJECT_VERSION: "2"
        INFOPLIST_FILE: Resources/Info.plist
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        SWIFT_STRICT_CONCURRENCY: minimal
