// █ dcj · dotcomjack.com · MIT
// Generated by dcj-tag. Edit mark/banner.txt, not this file.

#if canImport(Darwin)
import Darwin
#elseif canImport(Glibc)
import Glibc
#endif
import Foundation

let dcjBannerPlain = """
██████╗  ██████╗     ██╗
██╔══██╗██╔════╝     ██║
██║  ██║██║          ██║
██║  ██║██║     ██   ██║
██████╔╝╚██████╗╚█████╔╝
╚═════╝  ╚═════╝ ╚════╝
d o t c o m j a c k
"""

/// Bronze accent, RGB 140;106;47. Suppressed when stdout is not a TTY,
/// TERM is empty or "dumb", or NO_COLOR is set (even to an empty value).
var dcjBanner: String {
    let env = ProcessInfo.processInfo.environment
    let term = env["TERM"] ?? ""
    let allowColor = env["NO_COLOR"] == nil
        && term != "" && term != "dumb"
        && isatty(fileno(stdout)) == 1
    guard allowColor else { return dcjBannerPlain }
    let esc = "\u{001B}"
    return dcjBannerPlain
        .split(separator: "\n", omittingEmptySubsequences: false)
        .map { "\(esc)[38;2;140;106;47m\($0)\(esc)[0m" }
        .joined(separator: "\n")
}
